### ISSUE TITLE
compatibility with boost 1.83.0

### ISSUE THREAD

**Issue by GeTechG** [Ceber/boost_json_archive#4]
On boost 1.83.0 I could not compile, it gave me an error
```
C:\local\boost_1_83_0\boost\archive\detail\polymorphic_iarchive_route.hpp(93,32): error C2039: 'load_binary': is not a member of 'boost::archive::json_iarchive'
```
Similar error with `save_binary`

**Comment by Ceber** [comment]
Hello ! Thanks for feedback ! I'll take a look asap.

**Comment by Ceber** [comment]
Hello ! I cannot reproduce the issue without more details. A small code snippet that causes your compilation error could help.

**Comment by GeTechG** [comment]
I just serialize to json, adding an empty function to your code helped me
```
void load_binary(void *t, std::size_t size) { }
```
and also
```
void save_binary(const void *t, std::size_t size) { }
```
I don't use this, but it's a good idea to handle it in some way.
