### ISSUE TITLE
crashes on multidimensional array

### ISSUE THREAD

**Issue by GeTechG** [Ceber/boost_json_archive#5]
I have `std::array<std::array<std::array<int, 9>, 8>` in my code when trying to serialize my application crashes.
```
File: C:\local\boost_1_83_0\boost\json\value.hpp
Line: 2857

Expression: is_array()

For information on how your program can cause an assertion
failure, see the Visual C++ documentation on asserts
```

**Comment by Ceber** [comment]
Hello ! Thanks for having pointing this out !
I'll take a look asap. Do not hesitate to create a PR if you already have ideas on how to fix it.

Best regards.

**Comment by Ceber** [comment]
Hi again ! I tried something to cover your usecase. Let me know if it is better for you !

**Comment by GeTechG** [comment]
Yes it works, thanks for the fix.
